[package]
name = "shinespark"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
serde.workspace = true
axum.workspace = true
thiserror.workspace = true
anyhow.workspace = true
sqlx.workspace = true
serde_json.workspace = true
