[package]
name = "shinespark"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
serde.workspace = true
axum.workspace = true
thiserror.workspace = true
anyhow.workspace = true
sqlx.workspace = true
serde_json.workspace = true
config = "0.15.19"
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
password-hash = { version = "0.5.0", features = ["getrandom"] }
argon2 = "0.5.3"
pbkdf2 = { version = "0.12.2", features = ["simple"] }
sha2 = "0.10.9"
