[package]
name = "shinespark"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
axum = "0.8"
thiserror = "2.0"
anyhow = "1.0"
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres", "mysql", "sqlite"] }
serde_json = "1.0.149"
tracing = "0.1.44"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"] }
tower = { version = "0.5.3", features = ["util"] }
opentelemetry = { version = "0.22", features = ["trace"] }
opentelemetry_sdk = { version = "0.22", features = ["rt-tokio"] }
tracing-opentelemetry = "0.23"
reqwest = { version = "0.12", features = ["json"] }
reqwest-middleware = "0.4"
reqwest-tracing = { version = "0.5", features = ["opentelemetry_0_22"] }
config = "0.15.19"
password-hash = { version = "0.5.0", features = ["getrandom", "std"] }
argon2 = { version = "0.5.3", features = ["std"] }
pbkdf2 = { version = "0.12.2", features = ["simple", "std"] }
sha2 = { version = "0.10.9", features = ["std"] }
rand = "0.9"
opentelemetry-otlp = "0.31.0"
opentelemetry-stdout = "0.31.0"
futures-core = "0.3.32"

