[server]
host = "127.0.0.1"
port = 8080

[database]
url = "postgres://postgres:postgres@localhost:5432/shinespark"
max_connections = 10

[trace.console]
filter = "debug,axum=info,tower=info"
format = "compact"
buffer_limit = 256000
lossy = true

#[trace.file]
#filter = "info"
#directory = "logs"
#filename = "shinespark.log"
#format = "json"
#buffer_limit = 256000
#lossy = true

#[trace.otel]
#filter = "debug"
#endpoint = "http://localhost:4317"

[crypto.argon2]
memory_kib = 19456
iterations = 2
parallelism = 1
