[package]
name = "shinespark_app"
version = "0.1.0"
edition = "2024"

[dependencies]
shinespark.workspace = true
tokio.workspace = true
serde.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
axum.workspace = true